### ISSUE TITLE
Error by highload

### ISSUE THREAD

**Issue by byaka** [tcalmant/jsonrpclib#12]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in init
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```
after this happened server not responsed..
any ideas?

**Comment by tcalmant** [comment]
This happens if the client disconnects (or is disconnected) before reading the whole response of the server.

It also happens because jsonrpclib uses a single threaded server: in that case, an error during a request shuts down the server.
You can try using the ThreadMixIn to run a threaded server:
```python
import socketserver
from jsonrpclib import SimpleJSONRPCServer

class ThreadedJSONRPCServer(socketserver.ThreadMixIn, SimpleJSONRPCServer):
   pass

# Use ThreadedJSONRPCServer like SimpleJSONRPCServer
```

Also, could you activate jsonrpclib logs ?
```python
import logging
logging.getLogger('jsonrpclib').setLevel(logging.DEBUG)
```

**Comment by byaka** [comment]
Thx for solution, i'm add your code and start server. Now i'm wait :)

about logging-where it will placed? To strout?

**Comment by tcalmant** [comment]
By default, to stdout.
Take a look at the Python documentation of logging.basicConfig() to write logs to a file

-----Message d'origine-----
De : "BYaka" <notifications@github.com>
Envoyé : ‎28/‎01/‎2015 14:03
À : "tcalmant/jsonrpclib" <jsonrpclib@noreply.github.com>
Cc : "Thomas Calmant" <thomas.calmant@gmail.com>
Objet : Re: [jsonrpclib] Error by highload (#12)

Thx for solution, i'm add your code and start server. Now i'm wait :)
about logging-where it will placed? To strout?

**Comment by byaka** [comment]
yes, sorry for stupid question :[

**Comment by byaka** [comment]
3 days of test and no solution at all. BUT i'm locate a problem.
In jsonrpc methods i'm use some queries to mysql (over mysqldb module). And as i'm know, this lib cannot share connections over threads... (it's implement threadsafety level 1 only). I'm don't understand why i have this problem also without using ThreadedJSONRPCServer but..
Creating dedicated connection for every call of jsonrpc methods also bad solution, it take massive overhead...

**Comment by byaka** [comment]
without ThreadedJSONRPCServer lib use Greenlets? as i'm know in this case used monkey_patching. But libs like mysqldb (it's use C extension) cannot be patched. If i'm replace it by pure-python lib, any chance this solve my problem (without using ThreadedJSONRPCServer ofcourse)

**Comment by tcalmant** [comment]
A solution could be to have a threaded JSON-RPC server, in order to handle multiple clients, and to use a specific implementation of the ThreadPool for the SQL connections.

This ``SQLThreadPool`` would inherit from ``jsonrpclib.threadpool.ThreadPool``, and would override the ``__run()`` method: it should create the SQL connection right before its execution loop, and close it after the loop.
This SQL connection will have to be passed to the executed method (extra keyword argument, mandatory firt positional argument, ...)
=> this will imply some refactoring

If you need to return a result, the ``ThreadPool.enqueue()`` returns a ``FutureResult`` object, defined in ``jsonrpclib.threadpool``.

**Comment by byaka** [comment]
Thx for solution. If u think it's only solution, i will implement this. It's take a overhead (on creating a new connections every time) but i'm can't find more beautiful way :(
